// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyoKTPls4EcfbNmtjYDuBUiivlWsgHqkk',
    appId: '1:377200756049:web:b6633ecf1d2c72d7b9ff70',
    messagingSenderId: '377200756049',
    projectId: 'leoquotes-3a403',
    authDomain: 'leoquotes-3a403.firebaseapp.com',
    storageBucket: 'leoquotes-3a403.appspot.com',
    measurementId: 'G-28NYKXFECE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNFnoBpqcOBHkZjY1f0yqcbwE1LDabrcA',
    appId: '1:377200756049:android:5693bbaee6a4a7d9b9ff70',
    messagingSenderId: '377200756049',
    projectId: 'leoquotes-3a403',
    storageBucket: 'leoquotes-3a403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1jrrpZpdCDk0nJnHeQ--nBxKLU3i8q8U',
    appId: '1:377200756049:ios:9634e9242e49e72fb9ff70',
    messagingSenderId: '377200756049',
    projectId: 'leoquotes-3a403',
    storageBucket: 'leoquotes-3a403.appspot.com',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1jrrpZpdCDk0nJnHeQ--nBxKLU3i8q8U',
    appId: '1:377200756049:ios:9634e9242e49e72fb9ff70',
    messagingSenderId: '377200756049',
    projectId: 'leoquotes-3a403',
    storageBucket: 'leoquotes-3a403.appspot.com',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyoKTPls4EcfbNmtjYDuBUiivlWsgHqkk',
    appId: '1:377200756049:web:8956ebc1d437410db9ff70',
    messagingSenderId: '377200756049',
    projectId: 'leoquotes-3a403',
    authDomain: 'leoquotes-3a403.firebaseapp.com',
    storageBucket: 'leoquotes-3a403.appspot.com',
    measurementId: 'G-S8PQYRDDK8',
  );

}